# Provide some logic and data transformation to progress in the Workflow Template
---
- name: Decision Playbook - Auto Mirror Image
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    approved_registries:
      - quay.io
      - registry.redhat.io
      - nvcr.io
      - ghcr.io
      - gcr.io

  tasks:

    - name: Debug eda
      ansible.builtin.debug:
        msg: "{{ ansible_eda }}"

    # Simple example if you're just deciding on a single image
    #- name: Decide if the source image is in the list of approved registries
    #  ansible.builtin.assert:
    #    that: source_image.split('/')[0] in approved_registries
    #    fail_msg: "The source image {{ source_image }} is not in the list of approved registries: {{ approved_registries|join(', ') }}"
    #    success_msg: "The source image {{ source_image }} is in the list of approved registries: {{ approved_registries|join(', ') }}"

    - name: Read in the ServiceAccount token
      ansible.builtin.set_fact:
        k8s_auth_token: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"

    - name: Get the Pod definition from the cluster
      kubernetes.core.k8s_info:
        api_key: "{{ k8s_auth_token }}"
        api_version: v1
        kind: Pod
        namespace: "{{ ansible_eda.event.alert.labels.namespace }}"
        name: "{{ ansible_eda.event.alert.labels.pod }}"
      register: pod_info

    - name: Debug pod info
      ansible.builtin.debug:
        msg: "{{ pod_info }}"

    - name: Extract the container images from the Pod definition
      ansible.builtin.set_fact:
        container_images: "{{ container_images | default([]) + [image_item.image] }}"
      loop: "{{ pod_info.resources[0].spec.containers }}"
      loop_control:
        loop_var: image_item

    - name: Extract the initContainer images from the Pod definition
      ansible.builtin.set_fact:
        container_images: "{{ container_images | default([]) + [image_item.image] }}"
      loop: "{{ pod_info.resources[0].spec.initContainers }}"
      loop_control:
        loop_var: image_item

    - name: Create a list of approvied images
      when: image_item.split('/')[0] in approved_registries
      ansible.builtin.set_fact:
        approved_container_images: "{{ approved_container_images | default([]) + [image_item] }}"
      loop: "{{ container_images }}"
      loop_control:
        loop_var: image_item

    - name: Debug the approved container images
      ansible.builtin.debug:
        var: approved_container_images | default([])

    - name: Pass the container images along to the next Playbook in the Workflow Template
      ansible.builtin.set_stats:
        data:
          container_images: "{{ approved_container_images }}"
