---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: disconn-ocp-releases

resources:
  - buildah-disconnected.yml
  - ocp-release-tools.yml
  - skopeo-copy-disconnected.yml