---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-update-service

resources:
  - mcsb/global.yml
  - placementbindings/cvo-upstream-hub-osus.yml
  - placementrules/cvo-upstream-hub-osus.yml
  - policies/cvo-upstream-hub-osus.yml