---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocp-bin-tools
  namespace: ocp-bin-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem