---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: disconn-tekton

resources:
  - tasks/
  - config/
  - pipelines/

# Namespace Transformer - This will set the namespace to discon-tekton for resources that do not have one specified
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: disconn-tekton
    unsetOnly: true

# This doesn't work lol
# configurations:
#   - kConfig-namespace.yml
