---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: disconn-ocp-releases

resources:
  - shared/tasks/
  - shared/config/

# Namespace Transformer - This will set the namespace to discon-tekton for resources that do not have one specified
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: disconn-ocp-releases
    unsetOnly: true