# File: pipeline-binaries-build-container.yml
parameters:
  - name: REGISTRY_HOSTNAME # The hostname of the registry to push to
    type: string
    default: "quay.io"
  - name: REGISTRY_PATH     # Path to push to in the registry, eg your username
    type: string
    default: ""

  - name: REGISTRY_USERNAME # Needed for target push registry login
    type: string
    default: ""
  - name: REGISTRY_PASSWORD # Needed for target push registry login
    type: string
    default: ""

  - name: IMAGE_NAME     # Image Name for the container
    type: string
    default: ""
  - name: IMAGE_TAG      # Image tag, must be one tag for image build, defaults to latest
    type: string
    default: "latest"
  - name: CONTEXT    # Build context
    type: string
    default: "."
  - name: BUILD_DIRECTORY    # Working directory for the build
    type: string
    default: ""
  - name: CONTAINERFILE    # Name of the file used to build the container
    type: string
    default: "Containerfile"

stages:
  - stage: build_image

    variables:
      - name: currentDate
        value: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
      - name: sourceVersion
        value: $(Build.SourceVersion)

    pool:
      vmImage: ubuntu-latest

    jobs:
      - job: build
        displayName: Build Image
        steps:
          - bash: |
              if [ -z "$REGISTRY_USERNAME" ]; then
                echo "REGISTRY_USERNAME was not provided!"
                exit 1
              fi
              if [ -z "$REGISTRY_PASSWORD" ]; then
                echo "REGISTRY_PASSWORD was not provided!"
                exit 1
              fi
              if [ -z "$IMAGE_NAME" ]; then
                echo "IMAGE_NAME was not provided!"
                exit 1
              fi
            env:
              REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
              REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
              IMAGE_NAME: ${{ parameters['IMAGE_NAME'] }}

          - script: |
              commitHash=${sourceVersion:0:7}
              echo "Git Commit: ${sourceVersion}"
              echo "Short Git Commit: ${commitHash}"
              echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
            env: { sourceVersion: $(Build.SourceVersion) }

          - script: pip install ansible-builder==3.0.0

          - script: sudo apt-get install podman -y

          - bash: |
              podman build -t ${IMAGE_NAME}:${IMAGE_TAG} \
               -f ${CONTAINERFILE} \
               ${CONTEXT}

              podman login ${REGISTRY_HOSTNAME} -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}

              podman tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:${IMAGE_TAG}
              podman tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(commitHash)
              podman tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(sourceVersion)
              podman tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(currentDate)

              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:${IMAGE_TAG}
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(commitHash)
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(sourceVersion)
              podman push ${REGISTRY_HOSTNAME}/${REGISTRY_PATH}/${IMAGE_NAME}:$(currentDate)
            env:
              REGISTRY_HOSTNAME: ${{ parameters.REGISTRY_HOSTNAME }}
              REGISTRY_PATH: ${{ parameters.REGISTRY_PATH }}
              REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
              REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
              IMAGE_NAME: ${{ parameters['IMAGE_NAME'] }}
              IMAGE_TAG: ${{ parameters['IMAGE_TAG'] }}
            workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.BUILD_DIRECTORY }}"
              