---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Tekton Shared Resources - Tasks
  #- shared/tasks/buildah-disconnected.yml
  # Tekton Shared Resources - Setup
  - supporting/namespace.yml
  - supporting/serviceaccount-pipeline.yml
  - supporting/rbac-internal-registry.yml
  - supporting/imagestream.yml
  - supporting/configmap-registries.yml
  - supporting/configmap-root-ca.yml
  # Tekton Shared Resources - Pipelines
  - pipelines/ocp-binary-tools.yml
