---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: disconn-tekton

resources:
  - build-container-ocp-binary-tools.yml
  - build-container-ocp-release-tools.yml
  - build-container-osus-graph-data.yml
  - mirror-operators-to-registry.yml
  - ocp-release-mirror-from-dir.yml
  - ocp-release-mirror-to-dir.yml
  - ocp-release-mirror-to-registry.yml
  - skopeo-copy-disconnected-single.yml
  #- skopeo-copy-disconnected-multi.yml
