---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: disconn-tekton

resources:
  - build-ocp-release-tools-container.yml
  - ocp-binary-tools.yml
  - ocp-release-mirror-from-dir.yml
  - ocp-release-mirror-to-dir.yml
  - ocp-release-mirror-to-registry.yml
  - skopeo-copy-disconnected-single.yml
  #- skopeo-copy-disconnected-multi.yml
