apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: skopeo-copy-disconnected-single
spec:
  params:
    - name: SOURCE_IMAGE_URL
      description: ''
    - name: DESTINATION_IMAGE_URL
      description: ''
    - name: SRC_TLS_VERIFY
      description: ''
      default: 'true'
    - name: DEST_TLS_VERIFY
      description: ''
      default: 'true'
    - name: ARGS
      description: 'Extra arguements passed to skopeo copy command'
      default: '--all --preserve-digests'

    - name: AUTH_FILE
      default: '/tmp/authfile/auth.json'
      description: Path to authentication file to use for pulling/pushing images
      type: string
    - name: HTTP_PROXY
      default: ''
      description: HTTP proxy server (non-TLS requests).
      type: string
    - name: HTTPS_PROXY
      default: ''
      description: HTTPS proxy server (TLS requests).
      type: string
    - name: NO_PROXY
      default: ''
      description: Opt out of proxying HTTP/HTTPS requests.
      type: string
  tasks:
    - name: skopeo-copy-disconnected
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: skopeo-copy-disconnected
          - name: namespace
            value: openshift-pipelines
      params:
        - name: SOURCE_IMAGE_URL
          value: $(params.SOURCE_IMAGE_URL)
        - name: DESTINATION_IMAGE_URL
          value: $(params.DESTINATION_IMAGE_URL)
        - name: SRC_TLS_VERIFY
          value: $(params.SRC_TLS_VERIFY)
        - name: DEST_TLS_VERIFY
          value: $(params.DEST_TLS_VERIFY)
        - name: VERBOSE
          value: 'true'
        - name: ARGS
          value: "$(params.ARGS)"

        - name: AUTH_FILE
          value: "$(params.AUTH_FILE)"
        # Optional Proxy Configuration
        - name: HTTP_PROXY
          value: "$(params.HTTP_PROXY)"
        - name: HTTPS_PROXY
          value: "$(params.HTTPS_PROXY)"
        - name: NO_PROXY
          value: "$(params.NO_PROXY)"
      workspaces:
        - name: images_url
          workspace: images_url
        - name: authsecret
          workspace: authsecret
        - name: containerconfig
          workspace: containerconfig
        - name: root-ca-certs
          workspace: root-ca-certs
  workspaces:
    - name: images_url
      optional: true
    - name: authsecret
      optional: true
    - name: containerconfig
      optional: true
    - name: root-ca-certs
      optional: true