---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ocp-release-tools-
  labels:
    tekton.dev/pipeline: ocp-release-tools
spec:
  params:
    - name: VERBOSE
      value: "true"
    # Destination Image to Push to
    - name: IMAGE
      value: 'image-registry.openshift-image-registry.svc:5000/openshift/ocp-release-tools:latest'
    # Build context
    - name: CONTEXT
      value: openshift-release/
    # Override Source Git URL
    - name: URL
      value: 'https://github.com/kenmoini/disconnected-openshift.git'
    # Buildah things
    - name: BUILD_EXTRA_ARGS
      value: "--build-arg C_BASE_IMAGE=image-registry.openshift-image-registry.svc:5000/openshift/ocp-binary-tools:latest"
    - name: HTTP_PROXY
      value: "http://proxy.kemo.labs:3129"
    - name: HTTPS_PROXY
      value: "http://proxy.kemo.labs:3129"
    - name: NO_PROXY
      value: ".kemo.labs,.kemo.network,.local,.svc,localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
  pipelineRef:
    name: ocp-release-tools
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: build
      persistentVolumeClaim:
        claimName: ocp-release-tools

    - name: authsecret
      secret:
        items:
          - key: .dockercfg
            path: auth.json
        secretName: pipeline-internal-reg

# Optional in case you're pulling from a private repository and/or need to use a proxy
    - configMap:
        items:
          - key: registries.conf
            path: registries.conf
        name: mirror-registry-config
      name: containerconfig
    - configMap:
        items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
        name: root-ca-certs
      name: root-ca-certs