---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ocp-release-mirror-to-registry-
  labels:
    tekton.dev/pipeline: ocp-release-mirror-to-registry
spec:
  params:
    - name: DRY_RUN
      value: "false"
    - name: OCP_RELEASE
      value: "4.18.8"
    - name: ARCHITECTURE
      value: "multi"
    - name: MIRROR_METHOD
      value: 'direct'

    - name: LOCAL_REGISTRY
      #value: 'quay-quay-quay.apps.endurance-sno.d70.lab.kemo.network'
      value: 'disconn-harbor.d70.kemo.labs'
    - name: LOCAL_REGISTRY_PATH_OCP_RELEASE
      value: 'man-mirror/openshift-releases'

    #- name: EXTRA_OC_ARGS
    #  value: '--insecure'
    #- name: TLS_VERIFY
    #  value: 'false'

    - name: AUTH_FILE
      value: "/tmp/authsecret/auth.json"
    - name: HTTP_PROXY
      value: "http://proxy.kemo.labs:3129"
    - name: HTTPS_PROXY
      value: "http://proxy.kemo.labs:3129"
    - name: NO_PROXY
      value: ".kemo.labs,.kemo.network,.local,.svc,localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"

  pipelineRef:
    name: ocp-release-mirror-to-registry
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:

    - name: savepath
      persistentVolumeClaim:
        claimName: ocp-release-mirror

    - name: authsecret
      secret:
        items:
          - key: .dockerconfigjson
            path: auth.json
        secretName: combined-reg-secret

# Optional in case you're pulling from a private repository and/or need to use a proxy
    - configMap:
        items:
          - key: registries.conf
            path: registries.conf
        name: mirror-registry-config
      name: containerconfig
    - configMap:
        items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
        name: root-ca-certs
      name: root-ca-certs