---
- name: Automatic Remediation from Alert Manager for container images that are not able to pull
  hosts: all
  #execution_strategy: parallel
  sources:
    - name: Listen for alerts from Alert Manager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000

  rules:
    - name: debug lol
      condition: true
      action:
        print_event:
          pretty: true

    - name: debug lol
      condition: true
      action:
        debug:

    - name: Pod is stuck in image pull back off, try to mirror
      condition: event.alert.labels.alertname == "PodStuckImagePullBackOff" and event.alert.status == "firing"
      action:
        run_workflow_template:
          name: "Automatically Mirror Images"
          organization: "Default"
