variables:
  - group: RegistrySecrets

trigger:
  branches: # Branch names to include or exclude for triggering a run.
    include: [ 'main' ]
  paths: # File paths to include or exclude for triggering a run.
    include: [ 'binaries/' ]

schedules:
  - cron: '0 0 * * 0'
    displayName: Sunday night builds
    branches:
      include:
        - main

extends:
  template: ../../.azure/pipelines-build-container.yml
  parameters:
    REGISTRY_USERNAME: $(REGISTRY_USERNAME)
    REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
    REGISTRY_PATH: kenmoini
    IMAGE_NAME: ocp-install-utils
    BUILD_DIRECTORY: binaries/