variables:
  - group: RegistrySecrets

trigger:
  branches: # Branch names to include or exclude for triggering a run.
    include: [ 'main' ]
  paths: # File paths to include or exclude for triggering a run.
    include: [ 'execution-environments/binaries/' ]

schedules:
  - cron: '0 0 * * 0'
    displayName: Sunday night builds
    branches:
      include:
        - main

extends:
  template: ../../.azure/pipelines-build-ee.yml
  parameters:
    REGISTRY_USERNAME: $(REGISTRY_USERNAME)
    REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
    REGISTRY_PATH: kenmoini
    EE_IMAGE_NAME: ee-ocp-binaries
    EE_FOLDER_NAME: execution-environments/binaries