---
apiVersion: v1
kind: Secret
metadata:
  name: quay-config
stringData:
  config.yaml: |
    AUTHENTICATION_TYPE: Database
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: true
    ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    FEATURE_BUILD_SUPPORT: false
    FEATURE_DIRECT_LOGIN: true
    FEATURE_MAILING: false
    FEATURE_UI_V2: true
    FEATURE_UI_V2_REPO_SETTINGS: true
    FEATURE_AUTO_PRUNE: true
    FEATURE_PROXY_CACHE: true
    FEATURE_QUOTA_MANAGEMENT: true
    BROWSER_API_CALLS_XHR_ONLY: false
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Red Hat Quay
    DATABASE_SECRET_KEY: 0ce4f796-c295-415b-bf9d-b315114704b8
    SECRET_KEY: e8f9fe68-1f84-48a8-a05f-02d72e6eccba
    SUPER_USERS:
      - quayadmin
      - admin
      - kemo
    DISTRIBUTED_STORAGE_CONFIG:
        default:
            - LocalStorage
            - storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
        - default
    PREFERRED_URL_SCHEME: http
    DEFAULT_TAG_EXPIRATION: 2w
    TAG_EXPIRATION_OPTIONS:
        - 0s
        - 1d
        - 1w
        - 2w
        - 4w
        - 3y
