---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ocp-binary-tools-
  namespace: ocp-binary-tools
  labels:
    tekton.dev/pipeline: ocp-binary-tools
spec:
  pipelineRef:
    name: ocp-binary-tools
  taskRunTemplate:
    serviceAccountName: pipeline-internal-reg
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: build
      persistentVolumeClaim:
        claimName: ocp-binary-tools

    - name: authsecret
      secret:
        items:
          - key: .dockercfg
            path: auth.json
        secretName: pipeline-internal-reg

# Optional in case you're pulling from a private repository and/or need to use a proxy
    - configMap:
        items:
          - key: registries.conf
            path: registries.conf
        name: mirror-registry-config
      name: containerconfig
    - configMap:
        items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
        name: root-ca-certs
      name: root-ca-certs