---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: pipeline-internal-reg-token
  annotations:
    kubernetes.io/service-account.name: pipeline-internal-reg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-internal-reg
  annotations:
    openshift.io/internal-registry-pull-secret-ref: pipeline-internal-reg
