apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ocp-bin-tools
  namespace: ocp-bin-tools
spec:
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: 'https://github.com/kenmoini/disconnected-openshift.git'
        - name: REVISION
          value: main
        - name: SSL_VERIFY
          value: 'true'
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
        # Optional Proxy Configuration
        - name: HTTP_PROXY
          value: 'http://proxy.kemo.labs:3129'
        - name: HTTPS_PROXY
          value: 'http://proxy.kemo.labs:3129'
        - name: NO_PROXY
          value: '.kemo.labs,.kemo.network,.local,.svc,127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: build
    - name: buildah-disconnected
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/openshift/ocp-tools:latest'
        - name: DOCKERFILE
          value: binaries/Containerfile
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: binaries/
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
        # Optional Proxy Configuration
        - name: HTTP_PROXY
          value: 'http://proxy.kemo.labs:3129'
        - name: HTTPS_PROXY
          value: 'http://proxy.kemo.labs:3129'
        - name: NO_PROXY
          value: '.kemo.labs,.kemo.network,.local,.svc,127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah-disconnected
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: build
        - name: authsecret
          workspace: authsecret
        - name: containerconfig
          workspace: containerconfig
        - name: root-ca-certs
          workspace: root-ca-certs
  workspaces:
    - name: build
      optional: false
    - name: authsecret
      optional: true
    - name: containerconfig
      optional: true
    - name: root-ca-certs
      optional: true
