---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: disconn-ocp-releases

resources:
  # Tekton Shared Resources - Setup
  - supporting/namespace.yml
  - supporting/serviceaccount-pipeline.yml
  - supporting/rbac-internal-registry.yml
  - supporting/imagestream.yml
  - supporting/configmap-registries.yml
  - supporting/configmap-root-ca.yml
  # Tekton Shared Resources - Pipelines
  - pipelines/build-ocp-release-tools-container.yml
