---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-osus-graph-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem