version: 3

images:
  base_image:
    name: 'registry.access.redhat.com/ubi9/python-311:latest'

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  system:
    - java-17-openjdk-devel [platform:rpm]
    - gcc [platform:rpm]
    - systemd-devel [platform:rpm]
    #- pkgconf-pkg-config [platform:rpm]
    #- pkgconf [platform:rpm]
  python:
    - azure-servicebus
    - aiobotocore
    - aiohttp
    - aiokafka
    - gssapi
    - watchdog
    - systemd-python
    - dpath
    - requests
    - kubernetes
    - openshift
    - ansible-rulebook
  galaxy:
    collections:
      - ansible.eda
      - sabre1041.eda
      - community.general