
# ansible-builder build -f kitchen-sink.yml -t kitchen-sink-de:latest
# podman tag kitchen-sink-de:latest quay.io/kenmoini/ansible-kitchen-sink-de:latest
# podman push quay.io/kenmoini/ansible-kitchen-sink-de:latest
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
additional_build_files:
  - src: ansible.cfg
    dest: configs

images:
  base_image:
    #name: registry.access.redhat.com/ubi9/python-311:1-24.1695131442
    name: registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest
    #name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"

  galaxy: requirements.yml

  python:
    - ansible-rulebook
    - requests
    - kubernetes
  system:
    - java-17 [platform:rpm]
    - python3.11 [platform:rpm]
    - python3.11-devel [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - pkgconf [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]

additional_build_steps:
  append_final:
    #- RUN rm -rf /usr/bin/python3 && ln -s /usr/bin/python3.11 /usr/bin/python3
    - RUN mkdir -m 0775 -p /runner/env,inventory,project,artifacts} \
        && chmod -R g+rwx /runner \
        && chgrp -R root /runner \
        && touch /home/runner/.ansible/galaxy_token \
        && chmod -R g+rwx /home/runner \
        && chgrp -R root /home/runner \
        && chmod g+rw /home/runner/.ansible/galaxy_token \
        && chgrp root /home/runner/.ansible/galaxy_token
    - VOLUME /runner
    - ENV HOME=/home/runner
    - WORKDIR /runner

options:
  package_manager_path: /usr/bin/dnf